import os
import sys
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db_connection

CORE_POLICIES = [
    {
        "policy_id": "SEOUL-001",
        "name": "서울시 청년수당",
        "category_large": "일자리",
        "category_mid": "구직활동지원",
        "keyword": "구직활동, 취업준비, 활동지원금, 청년수당",
        "min_age": 19,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "매월 500,000원씩 최대 6개월간 총 300만원 체크카드 지급 및 취업 역량강화 멘토링 프로그램 제공",
        "explanation": "서울 거주 미취업 청년의 구직활동을 촉진하고 사회진입을 돕기 위해 매월 50만원을 6개월간 지원하는 대표 청년 복지 사업입니다.",
        "required_docs": "주민등록표초본(과거 5년 주소변동사항 표기)\n최종학력 졸업증명서(또는 수료증)\n고용보험 피보험자격 이력내역서(피보험자용)\n근로계약서 사본(단기근로자의 경우)",
        "apply_method": "서울청년몽땅정보통(youth.seoul.go.kr) 온라인 신청",
        "apply_url": "https://youth.seoul.go.kr/youthConts.do?key=200",
        "apply_period": "2026.03.11 ~ 2026.03.25 (상반기 정기모집)",
        "supervising_inst": "서울특별시 미래청년기획관",
        "operating_inst": "서울청년센터",
        "zip_codes": "서울특별시 전역 (관악구, 마포구, 강남구, 성동구, 영등포구 등 25개 자치구)",
        "target_job": "jobseeker,freelancer",
        "target_income": "income60,income120,income150",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-002",
        "name": "청년 부동산 월세 특별지원",
        "category_large": "주거",
        "category_mid": "월세지원",
        "keyword": "월세, 주거지원, 1인가구, 임대료",
        "min_age": 19,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "실제 납부하는 월세 범위 내에서 월 최대 200,000원씩 최대 12개월간(최대 240만원) 분할 입금 지원",
        "explanation": "독립 거주 무주택 청년의 주거비 부담을 덜어주기 위해 기준 중위소득 60% 이하 1인 가구 청년에게 월세를 지원합니다.",
        "required_docs": "임대차계약서 사본(확정일자 날인 필수)\n월세 이체 증빙서류(최근 3개월 입금확인증)\n주민등록등본 및 가족관계증명서(상세)\n통장사본",
        "apply_method": "복지로(bokjiro.go.kr) 온라인 신청 또는 동주민센터 방문",
        "apply_url": "https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00004661",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 접수)",
        "supervising_inst": "국토교통부 / 서울특별시 주택실",
        "operating_inst": "관할 자치구 주민센터",
        "zip_codes": "서울특별시 및 전국",
        "target_job": "jobseeker,employed,freelancer,student",
        "target_income": "income60",
        "target_household": "single"
    },
    {
        "policy_id": "SEOUL-003",
        "name": "청년 대중교통비 지원사업",
        "category_large": "생활･교통",
        "category_mid": "교통복지",
        "keyword": "교통비, 마일리지, 버스, 지하철, 대중교통",
        "min_age": 19,
        "max_age": 24,
        "age_limit_yn": "Y",
        "support_content": "연간 최대 100,000원 한도 내에서 대중교통 이용 금액의 20%를 교통마일리지로 환급",
        "explanation": "사회초년생 및 대학생 청년들의 이동권 보장을 위해 연간 최대 10만원의 교통마일리지를 사후 적립해 드립니다.",
        "required_docs": "본인 명의 교통카드(티머니, 신용/체크카드 후불교통)\n서울시 거주 사실 증빙(주민등록등본)",
        "apply_method": "서울청년몽땅정보통(youth.seoul.go.kr) 온라인 신청",
        "apply_url": "https://youth.seoul.go.kr/youthConts.do?key=2024102900001",
        "apply_period": "2026.04.01 ~ 2026.05.31 (상반기 정기 신청)",
        "supervising_inst": "서울특별시 미래청년기획관",
        "operating_inst": "서울청년센터",
        "zip_codes": "서울특별시 전역 (25개 자치구)",
        "target_job": "jobseeker,employed,freelancer,student",
        "target_income": "income60,income120,income150,unknown",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-004",
        "name": "희망두배 청년통장",
        "category_large": "금융･복지･문화",
        "category_mid": "자산형성",
        "keyword": "희망두배, 청년통장, 적금, 자산형성, 1:1매칭",
        "min_age": 18,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "매월 150,000원 저축 시 서울시 예산으로 동일 금액(15만원) 1:1 매칭 지원 (연간 360만원, 3년 만기 시 총 1,080만원 수령)",
        "explanation": "서울시 거주 일하는 청년이 주거, 결혼, 창업 등의 목돈을 마련할 수 있도록 저축액의 100%를 서울시가 매칭 적립해 드립니다.",
        "required_docs": "가입신청서 및 개인정보제공동의서\n주민등록초본(주소변동 포함)\n재직증명서(또는 고용보험 가입증명서)\n소득금액증명원(최근 1년)",
        "apply_method": "서울시 자산형성지원사업 포털(account.welfare.seoul.kr) 온라인 접수",
        "apply_url": "https://account.welfare.seoul.kr/",
        "apply_period": "2026.06.10 ~ 2026.06.28 (정기 공모)",
        "supervising_inst": "서울특별시 복지정책실",
        "operating_inst": "서울시복지재단",
        "zip_codes": "서울특별시 전역 (25개 자치구)",
        "target_job": "employed,freelancer",
        "target_income": "income60,income120",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-005",
        "name": "청년 임차보증금 대출이자 지원",
        "category_large": "주거",
        "category_mid": "대출이자지원",
        "keyword": "전세자금, 보증금대출, 이자지원, 전월세보증금",
        "min_age": 19,
        "max_age": 39,
        "age_limit_yn": "Y",
        "support_content": "전월세 보증금 대출(최대 7,000만원 한도)에 대해 연 최대 2.0% 대출이자 지원 (연 약 100만~140만원 이자 절감)",
        "explanation": "목돈 마련이 어려운 청년에게 전월세 보증금 대출 금리 중 연 2.0%를 서울시가 대신 은행에 지원합니다.",
        "required_docs": "주민등록등본 및 가족관계증명서\n임대차계약서 및 계약금(5% 이상) 납입영수증\n건강보험자격득실확인서\n소득금액증명원",
        "apply_method": "서울주거포털(housing.seoul.go.kr) 온라인 추천서 신청 후 하나은행 방문",
        "apply_url": "https://housing.seoul.go.kr/site/main/content/sh01_060500",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 신청 가능)",
        "supervising_inst": "서울특별시 주택실",
        "operating_inst": "하나은행 / 주택금융공사",
        "zip_codes": "서울특별시 전역",
        "target_job": "jobseeker,employed,freelancer",
        "target_income": "income60,income120,income150",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-006",
        "name": "서울시 취업날개 (면접정장 무료 대여)",
        "category_large": "일자리",
        "category_mid": "면접지원",
        "keyword": "면접정장, 취업날개, 정장대여, 면접지원, 넥타이, 구두",
        "min_age": 19,
        "max_age": 39,
        "age_limit_yn": "Y",
        "support_content": "취업 면접용 정장, 셔츠, 블라우스, 넥타이, 구두 일체 3박 4일간 연간 최대 10회 완전 무료 대여 (회당 5만원 상당)",
        "explanation": "취업 준비 청년들의 면접 비용 부담을 덜어주기 위해 서울시내 전문 대여업체 10여 곳에서 체형에 맞는 정장을 무료로 대여합니다.",
        "required_docs": "서울시 거주 증빙(주민등록등본 또는 신분증)\n면접 참석 사실 증빙서류(면접안내 문자, 이메일, 수험표 등)",
        "apply_method": "서울일자리포털(job.seoul.go.kr) 예약 후 대여점 방문",
        "apply_url": "https://job.seoul.go.kr/www/jobWing/jobWingIntro.do",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 신청 가능)",
        "supervising_inst": "서울특별시 경제정책실",
        "operating_inst": "서울일자리포털",
        "zip_codes": "서울특별시 전역 (25개 자치구)",
        "target_job": "jobseeker,student",
        "target_income": "income60,income120,income150,unknown",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-007",
        "name": "청년 국가자격증 및 어학시험 응시료 지원",
        "category_large": "교육･직업훈련",
        "category_mid": "역량강화",
        "keyword": "자격증, 토익, 토스, 기사, 한국사, 응시료",
        "min_age": 19,
        "max_age": 39,
        "age_limit_yn": "Y",
        "support_content": "토익, 오픽, 한국사, 국가기술자격증 등 실제 응시료 실비 연간 최대 100,000원 환급",
        "explanation": "취업 역량 개발을 위해 응시한 어학 및 자격증 시험 비용을 1인당 연 최대 10만원까지 서울시가 환급해 드립니다.",
        "required_docs": "시험 결제 영수증 및 응시확인서(성적표)\n주민등록초본\n통장사본",
        "apply_method": "서울청년몽땅정보통 온라인 신청",
        "apply_url": "https://youth.seoul.go.kr/youthConts.do?key=2024102900003",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 신청 가능)",
        "supervising_inst": "서울특별시 미래청년기획관",
        "operating_inst": "서울청년센터",
        "zip_codes": "서울특별시 전역",
        "target_job": "jobseeker,employed,student,freelancer",
        "target_income": "income60,income120,income150,unknown",
        "target_household": "single,family"
    },
    {
        "policy_id": "SEOUL-008",
        "name": "청년 마음건강 1:1 심리상담 바우처",
        "category_large": "금융･복지･문화",
        "category_mid": "마음건강",
        "keyword": "심리상담, 마음건강, 스트레스, 우울, 바우처",
        "min_age": 19,
        "max_age": 39,
        "age_limit_yn": "Y",
        "support_content": "전문 임상심리사와의 1:1 심층 상담 최대 10회기 무료 제공 (회당 8만원 상당, 총 80만원 지원)",
        "explanation": "진로, 취업, 대인관계 등으로 지친 청년들에게 마음건강 진단 및 맞춤형 전문 심리상담을 전액 무료로 지원합니다.",
        "required_docs": "온라인 자가진단표 작성\n서울시 거주 신분증",
        "apply_method": "서울청년몽땅정보통 온라인 신청",
        "apply_url": "https://youth.seoul.go.kr/youthConts.do?key=2024102900004",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 분기별 상시 접수)",
        "supervising_inst": "서울특별시 미래청년기획관",
        "operating_inst": "서울시 마음건강복지센터",
        "zip_codes": "서울특별시 전역",
        "target_job": "jobseeker,employed,student,freelancer",
        "target_income": "income60,income120,income150,unknown",
        "target_household": "single,family"
    },
    {
        "policy_id": "NAT-001",
        "name": "국민취업지원제도 1유형 (구직촉진수당)",
        "category_large": "일자리",
        "category_mid": "취업성공지원",
        "keyword": "국민취업지원제도, 구직촉진수당, 취업성공패키지, 국취제",
        "min_age": 15,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "구직촉진수당 월 500,000원 × 6개월 (최대 300만원) + 취업성공 시 최대 150만원 성공수당 지급",
        "explanation": "고용노동부 주관 한국형 실업부조 제도로, 1:1 직업상담 및 일경험 매칭과 함께 매월 50만원의 생계 및 구직촉진수당을 지원합니다.",
        "required_docs": "취업지원신청서 및 개인정보제공동의서\n주민등록등본\n가족관계증명서\n소득·재산 증빙 서류(건강보험료 납부확인서)",
        "apply_method": "고용24(work24.go.kr) 온라인 신청 또는 관할 고용복지플러스센터",
        "apply_url": "https://www.work24.go.kr/cm/c/a/0110/selectEmpSptPlcyDtl.do",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 신청 가능)",
        "supervising_inst": "고용노동부",
        "operating_inst": "전국 고용복지+센터",
        "zip_codes": "전국",
        "target_job": "jobseeker",
        "target_income": "income60,income120",
        "target_household": "single,family"
    },
    {
        "policy_id": "NAT-002",
        "name": "청년도약계좌 (정부기여금 매칭)",
        "category_large": "금융･복지･문화",
        "category_mid": "자산형성",
        "keyword": "청년도약계좌, 목돈마련, 적금, 정부기여금, 비과세",
        "min_age": 19,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "매월 최대 70만원 저축 시 정부기여금(월 최대 24,000원) 매칭 및 비과세 혜택 (5년 만기 시 최대 약 5,000만원 형성)",
        "explanation": "청년의 중장기 자산형성을 지원하기 위해 정부가 매월 최대 2.4만원의 기여금을 적립하고 이자소득 비과세를 제공합니다.",
        "required_docs": "신분증\n소득금액증명원(국세청 홈택스 발급)\n직전 과세기간 소득 확인서",
        "apply_method": "서민금융진흥원 청년도약계좌 포털 및 취급 은행 모바일 앱 신청",
        "apply_url": "https://ylaccount.kinfa.or.kr/main",
        "apply_period": "매월 초 가입신청 접수 (연중 상시)",
        "supervising_inst": "금융위원회",
        "operating_inst": "서민금융진흥원 및 시중은행",
        "zip_codes": "전국",
        "target_job": "employed,freelancer",
        "target_income": "income60,income120,income150",
        "target_household": "single,family"
    },
    {
        "policy_id": "NAT-003",
        "name": "K-패스 청년 환급 (대중교통비 30% 환급)",
        "category_large": "생활･교통",
        "category_mid": "교통환급",
        "keyword": "K패스, 대중교통, 지하철, 버스, 청년할인, 환급",
        "min_age": 19,
        "max_age": 34,
        "age_limit_yn": "Y",
        "support_content": "전국 대중교통 이용 금액의 30%를 다음 달 사후 현금 또는 마일리지 환급 (월 최대 60회, 연 약 21만원 절감)",
        "explanation": "월 15회 이상 대중교통 이용 시 청년층에게 이용 금액의 30%를 조건 없이 현금으로 환급해 드리는 전국 통합 교통복지 카드입니다.",
        "required_docs": "K-패스 제휴 카드(신용/체크카드) 발급\nK-패스 앱 회원가입 및 카드 등록",
        "apply_method": "K-패스 공식 홈페이지(korea-pass.kr) 또는 전용 모바일 앱",
        "apply_url": "https://korea-pass.kr/info/info_intro.do",
        "apply_period": "2026.01.01 ~ 2026.12.31 (연중 상시 신청 가능)",
        "supervising_inst": "국토교통부 대도시권광역교통위원회",
        "operating_inst": "한국교통안전공단",
        "zip_codes": "전국",
        "target_job": "jobseeker,employed,student,freelancer",
        "target_income": "income60,income120,income150,unknown",
        "target_household": "single,family"
    },
    {
        "policy_id": "LOCAL-GWANAK-01",
        "name": "관악 청년청 거점 취업역량 및 활동비 바우처",
        "category_large": "일자리",
        "category_mid": "지역특화지원",
        "keyword": "관악구, 관악청년청, 취업역량, 면접비, 멘토링",
        "min_age": 19,
        "max_age": 39,
        "age_limit_yn": "Y",
        "support_content": "1인당 취업역량 교육비 및 면접 활동비 연 최대 300,000원 관악사랑상품권 지원 + 공유오피스 무료 이용",
        "explanation": "청년 인구 비율 전국 1위 관악구 청년들을 위한 지역 맞춤형 직무 멘토링 및 구직 활동비 지원 패키지입니다.",
        "required_docs": "관악구 거주 확인 주민등록초본\n구직활동 계획서\n신분증 사본",
        "apply_method": "관악청년청 포털 온라인 신청",
        "apply_url": "https://www.gwanak.go.kr/site/gwanak/04/10403010100002020082705.jsp",
        "apply_period": "2026.03.15 ~ 2026.10.31 (선착순 모집)",
        "supervising_inst": "서울특별시 관악구 청년정책과",
        "operating_inst": "관악청년청",
        "zip_codes": "서울특별시 관악구",
        "target_job": "jobseeker,freelancer",
        "target_income": "income60,income120,income150",
        "target_household": "single,family"
    }
]

def seed_policies():
    conn, db_type = db_connection.init_db()
    cur = conn.cursor()
    print(f"[*] 데이터베이스 엔진: [{db_type.upper()}]에 서울시 핵심 청년 정책 12종 시딩 시작...")
    
    for p in CORE_POLICIES:
        raw = p.copy()
        raw["sbmsnDcmntCn"] = p["required_docs"]
        raw["plcySprtCn"] = p["support_content"]
        raw["plcyExplnCn"] = p["explanation"]
        
        db_connection.upsert_policy(cur, p, raw, db_type=db_type)
        
    conn.commit()
    conn.close()
    print(f"[OK] 총 {len(CORE_POLICIES)}건의 서울시 & 전국 핵심 청년정책 시딩 완료!")

if __name__ == "__main__":
    seed_policies()
